service: atcoder-auth
provider:
  name: aws
  runtime: rust
  memorySize: 128
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
      Resource:
        - "arn:aws:dynamodb:ap-northeast-1:*:table/AtCoderAuthCode"
        - "arn:aws:dynamodb:ap-northeast-1:*:table/AtCoderAuthToken"

package:
  individually: true

plugins:
  - serverless-rust

functions:
  authorize:
    handler: atcoder-auth.authorize
    events:
      - http:
          path: /api/authorize
          method: post
          cors: true
    environment:
      RUST_BACKTRACE: 1
  confirm:
    handler: atcoder-auth.confirm
    events:
      - http:
          path: /api/confirm
          method: post
          cors: true
  verify:
    handler: atcoder-auth.verify
    events:
      - http:
          path: /api/verify
          method: post
          cors: true
resources:
  Resources:
    AtCoderAuthCode:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AtCoderAuthCode
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: expired_at
          Enabled: true
    AtCoderAuthToken:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AtCoderAuthToken
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

